import React from "react";
import { Select, Checkbox } from "antd";
const { Option } = Select;

const ProcessorSelect = ({ processors, handleProcessor }) => {
  const processorsList = [
    "Intel Atom",
    "Intel Celeron",
    "Intel Pentium",
    "Intel Core i3",
    "Intel Core i5",
    "Intel Core i7",
    "Intel Core i9",
    "Intel Core m3",
    "Intel Core m5",
    "Intel Core m7",
    "Intel Xeon",
    "Apple Chip M1",
    "Apple Chip M2",
    "AMD A4",
    "AMD A6",
    "AMD A8",
    "AMD A10",
    "AMD A12",
    "AMD Ryzen 3",
    "AMD Ryzen 5",
    "AMD Ryzen 7",
    "Samsung’s Exynos",
    "Qualcomm’s snapdragon",
    "i5-7200U",
    "Intel Atom Dual –Core",
    "Intel Atom Octa –Core",
    "Intel Atom Quad –Core",
    "Intel Atom Single –Core",
    "Intel Celeron",
    "Intel Celeron D",
    "Intel Celeron M",
    "Intel Celeron N",
    "Intel Centrino",
    "Intel Core 2 Duo",
    "Intel Core 2 Quad",
    "Intel Core 2 Solo",
    "Intel Core Duo",
    "Intel Core i3 10th Gen",
    "Intel Core i3 11th Gen",
    "Intel Core i3 12th Gen",
    "Intel Core i3 13th Gen",
    "Intel Core i3 1st Gen",
    "Intel Core i3 2nd Gen",
    "Intel Core i3 3rd Gen",
    "Intel  Core i3 4th Gen",
    "Intel Core i3 5th Gen",
    "Intel Core i3 6TH Gen",
    "Intel Core i3 7th Gen",
    "Intel Core i3 8th Gen",
    "Intel Core i5 10th Gen",
    "Intel Core i5 12th Gen",
    "Intel Core i5 13th Gen",
    "Intel Core i5 1st Gen",
    "Intel Core i5 2nd Gen",
    "Intel Core i5 3rd Gen",
    "Intel Core i5 5th Gen",
    "Intel Core i5 -7200U",
    "Intel Core i5 7th Gen",
    "Intel Core i5 -8300H ",
    "Intel Core i5 9th Gen",
    "Intel Core i7 13TH Gen",
    "Intel Core i7 1st Gen",
    "Intel Core i7 2nd Gen",
    "Intel Core i7 3rd Gen",
    "Intel Core i7 4th Gen",
    "Intel Core i7 5th Gen",
    "Intel Core i7 6TH Gen",
    "Intel Core i7 7th Gen",
    "Intel Core i7 9th Gen",
    "Intel Core I7 Extreme 1st Gen",
    "Intel Core i7 Extreme 3rd Gen",
    "Intel Core I7 Extreme 5th Gen",
    "Intel Core i7 Extreme 6th Gen",
    "Intel Core i7 Extreme 7th Gen",
    "Intel Core i9 10th Gen",
    "Intel Core i9 13th Gen",
    "Intel Core i9 8th Gen",
    "Intel Core i9 9th Gen",
    "Intel Core M",
    "Intel Core M3",
    "Intel Core M3 6th Gen",
    "Intel Core M3 7th Gen",
    "Intel Core M5 6th Gen",
    "Intel Core Solo",
    "Intel Pentium",
    "Intel Pentium 4",
    "Intel Pentium 4 HT",
    "Intel Pentium 4 M",
    "Intel Pentium Dual – Core",
    "Intel Pentium Gold",
    "Intel Pentium II",
    "Intel Pentium III",
    "Intel Pentium III M",
    "Intel Pentium III Mobile",
    "Intel Pentium M",
    "Intel Pentium MMX",
    "Intel Pentium Mobile",
    "Intel Pentium  N4200",
    "Intel Pentium N- Series",
    "Intel Pentium Silver",
    "Intel Processor N",
    "Intel Xeon",
    "MediaTek MT8183",
    "Microsoft SQ1",
    "Microsoft SQ2",
    "Mobile AMD Sempron",
    "NVIDIA Tegra 3",
    "NVIDIA Tegra 4",
    "NVIDIA Tegra  K1",
    "Samsung Exynos 5 Dual",
    "VIA C7",
    "Not Specified",
    "Intel Core i5 11th Gen",
    "Intel Core i5 4th Gen",
    "Intel Core i5 6th Gen",
    "Intel Core i5 8th Gen",
    "Intel Core i7 10th Gen",
    "Intel Core i7 11th Gen",
    "Intel Core i7 12th Gen",
    "Intel Core i7 8th Gen",
    "AMD A10",
    "AMD A10 Quad-Core",
    "AMD A12",
    "AMD A4 Dual-Core",
    "AMD A6 Dual-Core",
    "AMD A6 Quad-Core",
    "AMD A6 Tri-Core",
    "AMD A8",
    "AMD A8 Quad-Core",
    "AMD A9",
    "AMD Athlon",
    "AMD Athlon 64",
    "AMD Athlon 64,64 M",
    "AMD Athlon 64 X2",
    "AMD Athlon Gold 3150U",
    "AMD Athlon ll",
    "AMD Athlon ll Neo",
    "AMD Athlon ll x2",
    "AMD Athlon Neo",
    "AMD Athlon Neo x2",
    "AMD Athlon Silver 3050U",
    "AMD Athlon x2",
    "AMD Athlon XP  XP- M",
    "AMD C-Series",
    "AMD Duron",
    "AMD E- Series",
    "AMD FX",
    "AMD K7",
    "AMD Opteron",
    "AMD Phenom",
    "AMD Phenom ll",
    "AMD Phenom ll X2",
    "AMD Phenom ll X4",
    "AMD Phenom  X4",
    "AMD Ryzen 5",
    "AMD Ryzen 5 2nd Gen",
    "AMD Ryzen  7",
    "AMD Ryzen 9",
    "AMD Sempron",
    "AMD Turion 64",
    "AMD Turion 64 X2",
    "AMD Turion ll",
    "AMD Turion X2",
    "AMD V-Series",
  ];

  return (
    <Select
      mode="multiple"
      placeholder={
        <span style={{ color: "#0E1B4D", fontWeight: "bold" }}>Processor</span>
      }
      value={processors}
      onChange={handleProcessor}
      style={{
        width: "100%",
        fontWeight: "bold",
        color: "#0E1B4D",
        height: 50,
      }}
      //   dropdownRender={renderProcessorDropdown}
      dropdownStyle={{ minWidth: 300 }}
    >
      {processorsList.map((option, key) => (
        <Checkbox key={key} value={option}>
          {option}
        </Checkbox>
      ))}
    </Select>
  );
};

export default ProcessorSelect;
