import React from "react";
import { Select, Checkbox } from "antd";
const { Option } = Select;

const ProcessorSelect = ({ processors, handleProcessor }) => {
  const processorsList = [
    "Intel Atom",
    "Intel Celeron",
    "Intel Pentium",
    "Intel Core i3",
    "Intel Core i5",
    "Intel Core i7",
    "Intel Core i9",
    "Intel Core m3",
    "Intel Core m5",
    "Intel Core m7",
    "Intel Xeon",
    "Apple Chip M1",
    "Apple Chip M2",
    "AMD A4",
    "AMD A6",
    "AMD A8",
    "AMD A10",
    "AMD A12",
    "AMD Ryzen 3",
    "AMD Ryzen 5",
    "AMD Ryzen 7",
    "Samsung’s Exynos",
    "Qualcomm’s snapdragon",
    "i5-7200U 206",
    "Intel Atom Dual –Core 12",
    "Intel Atom Octa –Core 1",
    "Intel Atom Quad –Core 17",
    "Intel Atom Single –Core 29",
    "Intel Celeron 1,311",
    "Intel Celeron D 2",
    "Intel Celeron M 22",
    "Intel Celeron N 1,258",
    "Intel Centrino 69",
    "Intel Core 2 Duo 381",
    "Intel Core 2 Quad 3",
    "Intel Core 2 Solo 1",
    "Intel Core Duo 46",
    "Intel Core i3 10th Gen.127",
    "Intel Core i3 11th Gen. 163",
    "Intel Core i3 12th Gen. 10",
    "Intel Core i3 13th Gen.3",
    "Intel Core i3 1st Gen . 82",
    "Intel Core i3 2nd Gen . 101",
    "Intel Core i3 3rd Gen. 82",
    "Intel  Core i3 4th Gen. 276",
    "Intel Core i3 5th Gen. 43",
    "Intel Core i3 6TH Gen. 104",
    "Intel Core i3 7th Gen. 117",
    "Intel Core i3 8th Gen. 118",
    "Intel Core i5 10th Gen. 311",
    "Intel Core i5 12th Gen. 116",
    "Intel Core i5 13th Gen. 21",
    "Intel Core i5 1st Gen. 147",
    "Intel Core i5 2nd Gen. 351",
    "Intel Core i5 3rd Gen. 503",
    "Intel Core i5 5th Gen. 295",
    "Intel Core i5 -7200U 130",
    "Intel Core i5 7th Gen. 357",
    "Intel Core i5 -8300H 7",
    "Intel Core i5 9th Gen. 37",
    "Intel Core i7 13TH Gen. 52",
    "Intel Core i7 1st Gen. 67",
    "Intel Core i7 2nd Gen. 86",
    "Intel Core i7 3rd Gen. 108",
    "Intel Core i7 4th Gen. 491",
    "Intel Core i7 5th Gen. 197",
    "Intel Core i7 6TH Gen. 841",
    "Intel Core i7 7th Gen. 243",
    "Intel Core i7 9th Gen. 120",
    "Intel Core I7 Extreme 1st Gen. 1",
    "Intel Core i7 Extreme 3rd Gen. 2",
    "Intel Core I7 Extreme 5th Gen 1",
    "Intel Core i7 Extreme 6th Gen. 1",
    "Intel Core i7 Extreme 7th Gen. 4",
    "Intel Core i9 10th Gen. 4",
    "Intel Core i9 13th Gen. 4",
    "Intel Core i9 8th Gen. 5",
    "Intel Core i9 9th Gen. 20",
    "Intel Core M 57",
    "Intel Core M3 9",
    "Intel Core M3 6th Gen. 3",
    "Intel Core M3 7th Gen. 8",
    "Intel Core M5 6th Gen. 13",
    "Intel Core Solo 1",
    "Intel Pentium 487",
    "Intel Pentium 4 31",
    "Intel Pentium 4 HT 3",
    "Intel Pentium 4 M 3",
    "Intel Pentium Dual – Core 52",
    "Intel Pentium Gold 34",
    "Intel Pentium II 3",
    "Intel Pentium III 7",
    "Intel Pentium III M 2",
    "Intel Pentium III Mobile  1",
    "Intel Pentium M 63",
    "Intel Pentium MMX  1",
    "Intel Pentium Mobile  3",
    "Intel Pentium  N4200 13",
    "Intel Pentium N- Series  38",
    "Intel Pentium Silver  108",
    "Intel Processor N 5",
    "Intel Xeon 63",
    "MediaTek MT8183 87",
    "Microsoft SQ1 3",
    "Microsoft SQ2 1",
    "Mobile AMD Sempron 1",
    "NVIDIA Tegra 3 1",
    "NVIDIA Tegra 4 2",
    "NVIDIA Tegra  K1 25",
    "Samsung Exynos 5 Dual 5",
    "VIA C7 1",
    "Not Specified  4,079",
    "Intel Core i5 11th Gen. 412",
    "Intel Core i5 4th Gen. 1,249",
    "Intel Core i5 6th Gen. 1,048",
    "Intel Core i5 8th Gen. 837",
    "Intel Core i7 10th Gen. 265",
    "Intel Core i7 11th Gen. 242",
    "Intel Core i7 12th Gen. 139",
    "Intel Core i7 8th Gen. 440",
    "AMD A10 209",
    "AMD A10 Quad-Core 44",
    "AMD A12 29",
    "AMD A4 Dual-Core 90",
    "AMD A6 Dual-Core 90",
    "AMD A6 Quad-Core 55",
    "AMD A6 Tri-Core 1",
    "AMD A8 244",
    "AMD A8 Quad-Core 36",
    "AMD A9 78",
    "AMD Athlon 137",
    "AMD Athlon 64 14",
    "AMD Athlon 64,64 M 2",
    "AMD Athlon 64 X2 27",
    "AMD Athlon Gold 3150U 22",
    "AMD Athlon ll 47",
    "AMD Athlon ll Neo 1",
    "AMD Athlon ll x2 10",
    "AMD Athlon Neo 4",
    "AMD Athlon Neo x2 3",
    "AMD Athlon Silver 3050U 24",
    "AMD Athlon x2  16",
    "AMD Athlon XP  XP- M 12",
    "AMD C-Series 4",
    "AMD Duron 5",
    "AMD E- Series 163",
    "AMD FX 17",
    "AMD K7 1",
    "AMD Opteron 1",
    "AMD Phenom 3",
    "AMD Phenom ll 26",
    "AMD Phenom ll X2 2",
    "AMD Phenom ll X4 1",
    "AMD Phenom  X4 2",
    "AMD Ryzen 5 580",
    "AMD Ryzen 5 2nd Gen. 7",
    "AMD Ryzen  7 214",
    "AMD Ryzen 9 5",
    "AMD Sempron 25",
    "AMD Turion 64 45",
    "AMD Turion 64 X2 130",
    "AMD Turion ll 60",
    "AMD Turion X2 43",
    "AMD V-Series  4",
  ];

  return (
    <Select
      mode="multiple"
      placeholder={
        <span style={{ color: "#0E1B4D", fontWeight: "bold" }}>Processor</span>
      }
      value={processors}
      onChange={handleProcessor}
      style={{
        width: "100%",
        fontWeight: "bold",
        color: "#0E1B4D",
        height: 50,
      }}
      //   dropdownRender={renderProcessorDropdown}
      dropdownStyle={{ minWidth: 300 }}
    >
      {processorsList.map((option, key) => (
        <Checkbox key={key} value={option}>
          {option}
        </Checkbox>
      ))}
    </Select>
  );
};

export default ProcessorSelect;
